// swift-tools-version: 6.0
import PackageDescription

// Six trivial binary xcframework targets (generated by make-xcframeworks.sh),
// one module that depends on all of them ("Core"), and two thin products on top
// of it. The BuildTwice command plugin builds the products through
// PackageManager.build(...) the way a bundling plugin would.
let frameworks = ["Alpha", "Beta", "Gamma", "Delta", "Epsilon", "Zeta"]

let package = Package(
    name: "XCFrameworkOrderRepro",
    platforms: [.macOS(.v14)],
    products: [
        .library(name: "ConsumerA", type: .dynamic, targets: ["ConsumerA"]),
        .library(name: "ConsumerB", type: .dynamic, targets: ["ConsumerB"]),
        .plugin(name: "BuildTwice", targets: ["BuildTwice"]),
    ],
    targets: frameworks.map { .binaryTarget(name: $0, path: "XCFrameworks/\($0).xcframework") } + [
        .target(name: "Core", dependencies: frameworks.map { .target(name: $0) }),
        .target(name: "ConsumerA", dependencies: ["Core"]),
        .target(name: "ConsumerB", dependencies: ["Core"]),
        .plugin(
            name: "BuildTwice",
            capability: .command(
                intent: .custom(
                    verb: "build-twice",
                    description: "Builds products via PackageManager.build and reports whether the generated llbuild manifest changed between plans"
                )
            )
        ),
    ]
)
