name: Performance test

on:
  workflow_dispatch:
    inputs:
    container:
      type: string
      description: "The container that the performance tests should run in"
      default: "swift:latest"
    package_path:
      type: string
      description: The directory in the repository that contains a package, which depends on ordo-one/package-benchmark and can run performance measurements.
      default: Benchmarks
    comment_header:
      type: string
      description: |
        If the performance has changed, this text will be prepended to the comment that contains the performance measurements.
        This can be either for performance improvements or regressions.
      default: |
        This PR has changed performance characteristics. Please review that the measurements reported below are expected. If these are improvements, thanks for improving the performance.
  workflow_call:
    inputs:
      container:
        type: string
        description: "The container that the performance tests should run in"
        default: "swift:latest"
      package_path:
        type: string
        description: The directory in the repository that contains a package, which depends on ordo-one/package-benchmark and can run performance measurements.
        default: Benchmarks
      comment_header:
        type: string
        description: |
          If the performance has changed, this text will be prepended to the comment that contains the performance measurements.
          This can be either for performance improvements or regressions.
        default: |
          This PR has changed performance characteristics. Please review that the measurements reported below are expected. If these are improvements, thanks for improving the performance.

jobs:
  measure_performance:
    name: Measure performance
    runs-on: ubuntu-latest
    #container:
    #  image: ${{ inputs.container }}
    #  options: "--cap-add SYS_ADMIN --privileged"
    timeout-minutes: 60
    permissions:
      pull-requests: write
    steps:
      - name: Install libjemalloc-dev
        run: sudo -n apt-get update && sudo apt-get install -y libjemalloc-dev
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Mark the workspace as safe
        # https://github.com/actions/checkout/issues/766
        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}
      - name: setup
        continue-on-error: true
        run: |
          echo "per stats:"
          perf stat sleep 1
          echo "Change perf event:"
          sudo sysctl -w kernel.perf_event_paranoid=-1
          echo "Instructions again:"
          perf stat -e instructions sleep 1
            
      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v3
      - name: Measure PR performance
        run: |
          git clone https://github.com/ordo-one/package-benchmark.git
          swift package --package-path package-benchmark/Benchmarks benchmark --target Basic --filter Basic

